import { RGBA, SyntaxStyle } from "@opentui/core"

export const theme = {
  bg: "#0b1020",
  panel: "#111827",
  panelAlt: "#0f172a",
  codeBg: "#0b1220",
  codeBorder: "#475569",
  border: "#334155",
  borderActive: "#7dd3fc",
  text: "#e5e7eb",
  codeText: "#dbeafe",
  muted: "#94a3b8",
  subtle: "#64748b",
  accent: "#38bdf8",
  accentSoft: "#1e3a5f",
  good: "#86efac",
  warn: "#facc15",
  danger: "#fda4af",
}

export const markdownStyle = SyntaxStyle.fromStyles({
  "markup.heading": { fg: RGBA.fromHex("#bfdbfe"), bold: true },
  "markup.heading.1": { fg: RGBA.fromHex(theme.accent), bold: true },
  "markup.heading.2": { fg: RGBA.fromHex("#93c5fd"), bold: true },
  "markup.heading.3": { fg: RGBA.fromHex("#bfdbfe"), bold: true },
  "markup.heading.4": { fg: RGBA.fromHex("#dbeafe"), bold: true },
  "markup.heading.5": { fg: RGBA.fromHex("#dbeafe"), bold: true },
  "markup.heading.6": { fg: RGBA.fromHex("#dbeafe"), bold: true },
  "markup.strong": { fg: RGBA.fromHex(theme.text), bold: true },
  "markup.italic": { fg: RGBA.fromHex("#c4b5fd"), italic: true },
  "markup.strikethrough": { fg: RGBA.fromHex(theme.subtle), dim: true },
  "markup.link": { fg: RGBA.fromHex(theme.accent), underline: true },
  "markup.link.label": { fg: RGBA.fromHex("#67e8f9"), underline: true },
  "markup.link.url": { fg: RGBA.fromHex(theme.subtle), underline: true, dim: true },
  "markup.raw": { fg: RGBA.fromHex("#fde68a"), bg: RGBA.fromHex("#1f2937") },
  "markup.list": { fg: RGBA.fromHex("#c4b5fd") },
  "markup.quote": { fg: RGBA.fromHex("#cbd5e1"), italic: true },
  conceal: { fg: RGBA.fromHex(theme.subtle), dim: true },
  comment: { fg: RGBA.fromHex(theme.subtle), italic: true },
  keyword: { fg: RGBA.fromHex("#c4b5fd"), bold: true },
  string: { fg: RGBA.fromHex("#86efac") },
  number: { fg: RGBA.fromHex("#fbbf24") },
  boolean: { fg: RGBA.fromHex("#fbbf24") },
  constant: { fg: RGBA.fromHex("#fbbf24") },
  function: { fg: RGBA.fromHex("#93c5fd") },
  method: { fg: RGBA.fromHex("#93c5fd") },
  type: { fg: RGBA.fromHex("#67e8f9") },
  variable: { fg: RGBA.fromHex(theme.codeText) },
  property: { fg: RGBA.fromHex("#bae6fd") },
  operator: { fg: RGBA.fromHex("#f0abfc") },
  punctuation: { fg: RGBA.fromHex("#94a3b8") },
  tag: { fg: RGBA.fromHex("#fda4af") },
  attribute: { fg: RGBA.fromHex("#fcd34d") },
  default: { fg: RGBA.fromHex(theme.text) },
})
